export const mediaData2 = [
    { imageSrc: '/img/media/GODZILLA_AWAKENING.jpg', title: 'Godzilla: Awakening (2014)', detalhes: 'Escrito por Max Borenstein e Greg Borenstein - Ilustrado por Eric Battle, Yvel Guichet e Alan Quah',imageMDL:'/img/hq/godzillaawakening_destaquer.jpg', description: 'Delve into an incredible mystery, generations in the making. At the dawn of the atomic age, humanity awakens lifeforms beyond imagination, unleashing monumental forces of nature. This explosive, larger-than-life adventure is the perfect way for fans to experience the new Godzilla before seeing it in theaters.' },
    { imageSrc: '/img/media/424238748383828383.jpeg', title: 'Skull Island: The Birth of Kong (2017)', description: 'Descrição do Skull Island: The Birth of Kong (2017)' },
    { imageSrc: '/img/media/Godzilla_Aftershock_final_cover.jpg', title: 'Godzilla: Aftershock (2019)', imageMDL:'/img/hq/IMG_20190330_175234.jpg', description: 'The King of the Monsters becomes an endangered species as an ancient terror rises from the depths of the earth, unleashing a series of devastating earthquakes, and driven by an unstoppable primal instinct that will test Godzilla like never before.' },
    { imageSrc: '/img/media/Godzilla_Dominion_cover.jpg', title: 'Godzilla Dominion (2021)', imageMDL: '/img/hq/5723997.webp', description: 'A unique story that picks up after the events of the film Godzilla: King of the Monsters, where the Titans have risen and the reign of Godzilla has begun. As told entirely from Godzilla’s point of view, the graphic novel brings new insights into the King of Monsters: his habitats, ancient rivalries, challenges, and encounters with new Titans. As his new era of dominance is tested, a coming confrontation with another King looms.' },
    { imageSrc: '/img/media/Kingdom_Kong_cover.jpg', title: 'Kingdom Kong (2021)', description: 'Descrição do Kingdom Kong (2021)' },
    { imageSrc: '/img/media/Skull_island_poster2.jpeg', title: 'Skull Island (2023)', description: 'Descrição do Skull Island (2023)' },
    { imageSrc: '/img/media/3IYqVM2jEHn8j9ZVETE0VcNvGoz.jpg', title: 'Monarch: Legado de Monstros (2023)', detalhes: 'Escrito por: Chris Black, Matt Fraction', imageMDL: '/img/modal/godzilla-monarch.gif', description: 'Após a sangrenta batalha entre Godzilla e os Titãs que devastou São Francisco e a surpreendente revelação de que os monstros são reais, “Monarch” conta a história de dois irmãos que seguem os passos do pai para descobrir a ligação da sua família com a organização secreta conhecida como Monarch. As pistas os levarão ao mundo dos monstros e, por fim, ao oficial do exército Lee Shaw (interpretado por Kurt Russell e Wyatt Russell), na década de 1950 e meio século depois, quando Monarch é ameaçada pelo que Shaw sabe. Abrangendo três gerações, esta saga dramática revela segredos ocultos e mostra como eventos épicos e chocantes podem impactar nossas vidas.' },
    { imageSrc: '/img/media/F1sWYx-X0AIoqCG.jpeg', title: 'Liga da Justiça Vs. Godzilla Vs. Kong (2023)', imageMDL:'/img/hq/justice-league-vs-godzilla-vs-kong-special-edition-header.webp',description: 'The cataclysmic crossover event of the year is here as the DC Universe clashes with Legendary’s Monsterverse in Justice League vs. Godzilla vs. Kong.' },
    { imageSrc: '/img/media/Godzilla-x-kong-the-hunted-9781681161280_xlg.jpg', title: 'Godzilla x Kong: The Hunted (2024)', imageMDL:'/img/hq/Trophies_of_skull_island_creatures_by_mnstrfrc_dgb6npw.png', description: 'A twisted Skull Island trophy hunter baits his trap and sets his sights on the biggest game of all deep within the Hollow Earth in the official prequel graphic novel to the upcoming film Godzilla x Kong: The New Empire.' },

];